# github action to deploy HtmlLearning to azure

name: TESTAPIHAMZA
on:
 push:
    branches:
      - main 

env:
  AZURE_WEBAPP_NAME: "testapihamza"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore ./Test.API/Test.API.csproj
    - name: Build
      run: dotnet build ./Test.API/Test.API.csproj --configuration Release --no-restore
    # publish
    - name: Publish
      run: dotnet publish ./Test.API/Test.API.csproj --configuration Release --output ./publish 
      #deploy
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.TEST_API_HAMZA_SECRET }}
        package: ./publish 
